sudo: required
# dist: trusty
language: node_js
node_js:
  - 12.4.0

env:
  global:
    - NO_AT_BRIDGE=1 # Needed for dbus to work.
    - CC=clang
    - CXX=clang++
    - npm_config_clang=1

before_install:
  - npm i -g npm@latest

install:
  - npm install

before_script:
  - |
    export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; sleep 3;
    eval $(dbus-launch --sh-syntax);
    eval $(echo -n "" | /usr/bin/gnome-keyring-daemon --login);
    eval $(/usr/bin/gnome-keyring-daemon --components=secrets --start);
    /usr/bin/python -c "import gnomekeyring;gnomekeyring.create_sync('login', '');";
script:
  - npm run check
  - npm run test:node
  # - if [ -n "$NODE" ]; then npm run test:node; fi
  # - if [ -n "$ELECTRON" ]; then npm run test:electron; fi

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libsecret-1-dev
      - gnome-keyring
      - python-gnomekeyring
