sudo: required
dist: trusty
language: node_js
node_js:
  - 10.2.1
before_install:
  - npm i -g npm@latest
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libsecret-1-dev
      - gnome-keyring
      - libstdc++6
script: 
  - npm test
