sudo: required
# dist: trusty
language: node_js
node_js:
  - 10.2.1
before_install:
  - npm i -g npm@latest
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - xvfb
      - libsecret-1-dev
      - libdbus-1-dev
      - gnome-keyring
      - libstdc++6
      - python-gnomekeyring
script: 
  - xvfb-run ./scripts/ci.sh
env:
  - CC=clang CXX=clang++ npm_config_clang=1
before_script:
  - |
    dbus-launch /usr/bin/python -c \
      "import gnomekeyring;gnomekeyring.create_sync('login', '');"