language: node_js
node_js:
  - 10
env:
  - CXX=g++-4.8
before_install:
  - npm install -g npm@latest
    - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libkrb5-dev
      - libsecret-1-dev
      - libstdc++6
script: npm test
